### PR TITLE
Updated http URLs to https

### PR DESCRIPTION
**Pull request by elucify**
To improve end user security and privacy, and by Federal government mandate OMB memo M-08-023, NCBI will be moving all web services to HTTPS-only by September 30, 2016.

I've gone over the bioperl source code and replaced all references http://www.ncbi to https.

While we intend to provide redirects for GET and HEAD, POST and other non-safe methods will likely not be redirected; in particular, epost will cease to function over http when we move to https.

For more information:

http://www.ncbi.nlm.nih.gov/news/06-10-2016-ncbi-https/
https://https.cio.gov/
subscribe to the utilities-announce mailing list at https://www.ncbi.nlm.nih.gov/mailman/listinfo/utilities-announce

The Federal deadline is December 31, but the NLM deadline is September 30, 2016.

### CODE REVIEW

**Comment by cjfields** [comment]
@elucify We had a number of the various HTTPS changes already incorporated in, but there are a number of additional URL changes we missed so I have gone ahead and merged this in.  Thanks!

**Comment by elucify** [comment]
Thank you. Is there an official release number where this will be available, or should people just pull master?

**Comment by cjfields** [comment]
@elucify it will be in the upcoming 1.7 release; we have a few release candidates out already, though I may do a few more (I realized we have a couple of split modules that we should pull back in for this release).

**Comment by elucify** [comment]
Checking to see if 1.7 is released yet, and, if so, where I can point users to download it. Thanks.

**Comment by cjfields** [comment]
@elucify we're awaiting the impending changes w/ removing GIs at NCBI; we don't anticipate any fallout except with test results changing, but I don't want to send out a release that will possibly break within a few weeks.  See issue #196

**Comment by cjfields** [comment]
@elucify we're awaiting the impending changes w/ removing GIs at NCBI.  We don't anticipate any fallout except with test results changing (and these would be via network tests), but I don't want to send out a release that will possibly break within a few weeks.  See issue #196

**Comment by elucify** [comment]
OK thank you

**Pull request merged**
