### PR TITLE
adds research notice to the readme

### PR DESCRIPTION
**Pull request by yochannah**
... so contributors know metrics may be taken over the next 12 months :) let me know if you have any questions.

### CODE REVIEW

**Comment by carandraug** [comment]
README is the file that users of the software should read first. It should provide a general overview of the software. They may not necessarily even read it on github, they might be reading it from the provided installation package.

I don't think this is information for the README file. I'm not sure where it should be, maybe just an email to the dev team works as a heads up?

**Comment by yochannah** [comment]
It's interesting seeing how different projects use a readme :) 

How about the hacking file instead? An email only hits inboxes once and might not be accessible to people who want to make a PR or issue after the email is sent.

**Comment by hlapp** [comment]
The way this is written can lead to one to believe that this repository is not otherwise (i.e., unless notified in this way) participating in research studies. This is, however, not true, and would be very misleading. Public repositories on GitHub are routinely participating in research studies, whether notified or not, as a result of GitHub's policies and terms of use permitting certain programmatic access to public repositories' data.

The desire of the specific research project here to notify this community of its plans is certainly a commendable and welcome ethical disclosure practice. But I suggest placing this in a way that (a) best reaches everyone (for example, post it as an issue on the tracker, and/or as an email to the community mailing list); and (b) makes it clear that this is a notification from a specific project, and that it should not be taken to suggest that no such data will be collected by others in the absence  of such notification.

**Comment by yochannah** [comment]
@hlapp thanks - so how about re-word from current wording to say: 

>  Please note that this repository is participating in a study into sustainability of open source projects. Data will be gathered about this repository for approximately the next 12 months, starting from June 2021. Data collected will include number of contributors, number of PRs, time taken to close/merge these PRs, and issues closed. For more information, please visit [the informational page](https://sustainable-open-science-and-software.github.io/) or download the [participant information sheet](https://sustainable-open-science-and-software.github.io/assets/PIS_sustainable_software.pdf).
> 
> This notice has been placed in compliance with the ethics review board process from the Department of Computer Science at University of Manchester in the United Kingdom. The presence of this notice does not exclude other projects from gathering metrics via GitHub's open-access API. 

and then: 

1. close this pr and open an issue instead
2. email bioperl-l@bioperl.org and link to the issue

**Comment by hlapp** [comment]
@yochannah sounds good, though for full clarity why not name and link to the specific study in "_is participating in a study_" rather than leaving that sound generic and up to guess work for which specific study it refers to.

**Comment by yochannah** [comment]
perfect, and on it! Thanks so much :)

**Pull request closed without merging**
