### PR TITLE
TravisCI: cache Perl dependencies

### PR DESCRIPTION
**Pull request by zmughal**
This makes the builds run faster and use fewer resources.

See <https://github.com/bioperl/bioperl-live/issues/242>.

### CODE REVIEW

**Comment by hlapp** [comment]
The difference in build times between this PR ([Travis build 263739597](https://travis-ci.org/bioperl/bioperl-live/builds/263739597)) and the latest on master ([Travis build 263952573](https://travis-ci.org/bioperl/bioperl-live/builds/263952573), which doesn't include this yet) seems small, and in fact not obviously distinguishable from what might be attributable to variation due to load on Travis. Are you sure your change should fully convey the benefits from caching, to the extent that they exist?

**Comment by zmughal** [comment]
I think the overhead of downloading and unpacking the cache can sometimes be larger than the time gained of not having to install any modules.

In the specific case you linked, some of the builds had not stored a cache yet so to do a proper comparison we have to look at each build. I did a rebase and added another commit just now to make sure that all of the builds have caches and this brought the total build time down from 1hr13m to 58m.

But after adding a few empty commits to see the spread, cached builds ranged from 59m to 1hr20m.

It seems like using a cache is not useful unless we have dependencies that take a while to build.

---

I also so these test errors crop up when using the cache in [build 831.2](https://travis-ci.org/bioperl/bioperl-live/jobs/264133638), but I'm not sure if they are relevant:

```
------------- EXCEPTION: Bio::Root::Exception -------------

MSG: This index file is type [Bio::Index::BlastTable] - Can't access it with module for [Bio::Index::Blast]

STACK: Error::throw

STACK: Bio::Root::Root::throw Bio/Root/Root.pm:447

STACK: Bio::Index::Abstract::_type_and_version Bio/Index/Abstract.pm:495

STACK: Bio::Index::Abstract::open_dbm Bio/Index/Abstract.pm:415

STACK: Bio::Index::Abstract::new Bio/Index/Abstract.pm:162

STACK: Bio::Index::Blast::new Bio/Index/Blast.pm:143

STACK: t/LocalDB/Index/Blast.t:20

-----------------------------------------------------------

# Looks like your test exited with 2 just after 3.

t/LocalDB/Index/Blast.t ................ Dubious, test returned 2 (wstat 512, 0x200)

Failed 23/26 subtests 
```

```
------------- EXCEPTION: Bio::Root::Exception -------------

MSG: This index file is from version [1.007001] - You need to rebuild it to use module version [0.2]

STACK: Error::throw

STACK: Bio::Root::Root::throw Bio/Root/Root.pm:447

STACK: Bio::Index::Abstract::_type_and_version Bio/Index/Abstract.pm:493

STACK: Bio::Index::Abstract::open_dbm Bio/Index/Abstract.pm:415

STACK: Bio::Index::Abstract::new Bio/Index/Abstract.pm:162

STACK: Bio::Index::AbstractSeq::new Bio/Index/AbstractSeq.pm:93

STACK: t/LocalDB/Index/Index.t:27

-----------------------------------------------------------

# Looks like your test exited with 2 just after 10.

t/LocalDB/Index/Index.t ................ Dubious, test returned 2 (wstat 512, 0x200)

Failed 63/73 subtests 
```

**Comment by hlapp** [comment]
I just encountered this failure too in #245. It went away after restarting the one particular build that failed with this.

Hard to say whether that's got anything to do with this or not. (The code change obviously wasn't there in #245.)

**Comment by hlapp** [comment]
I'm also still not seeing a substantial drop in time to execute. Hence, I'm not sure it's worth adding this if there are potential random effects on tests causing fluke failures, because these would be quite hard to track down.

**Comment by zmughal** [comment]
I'll close this for now. It should be easy to revisit later if we do need it.

**Pull request closed without merging**
