### PR TITLE
Restore missing MANIFEST.

### PR DESCRIPTION
**Pull request by jkeenan**
When running ./BUILD on source code checked out from github.com, got warning
about missing or corrupt MANIFEST.  Followed instruction to run ./Build
manifest.

### CODE REVIEW

**Comment by cjfields** [comment]
@jkeenan forgot to mention in the initial email, we generate the MANIFEST per run, but we can include this as a stub.

**Comment by cjfields** [comment]
The problem may be that the MANIFEST auto-generated may be problematic.  Let's see what happens if I try to set up a release; will test that this week

**Comment by cjfields** [comment]
Hi @jkeenan currently we add the MANIFEST at the end during readying code for a release, took me a while to step through it and find this.  We probably should generate this during the initial steps in Build somehow.  Will see what we can do.

**Comment by jkeenan** [comment]
On 07/07/2016 04:53 PM, Chris Fields wrote:
> Hi @jkeenan currently we add the MANIFEST at the end during readying code for a release, took me a while to step through it and find this.  We probably should generate this during the initial steps in Build somehow.  Will see what we can do.
>

I'm more familiar with ExtUtils-MakeMaker's workflow than with 
Module-Build's.  But I suspect that it would be easy to:

$ touch MANIFEST MANIFEST.SKIP
$ git add MANIFEST*
$ git commit -m "Add MANIFEST and SKIP to version control"
$ perl Build.PL
$ ./Build
$ ./Build manifest
$ ./Build test
$ git status  # note changes in MANIFEST (and possibly MANIFEST.SKIP)
$ git add MANIFEST*
$ git commit -m "Update MANIFEST and SKIP'
$ ./Build dist
etc.

Jim Keenan

**Pull request merged**
