### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by cjfields**
Proposed code of conduct.  See #365 .

### CODE REVIEW

**Review by hlapp — APPROVED** [review]
Not much to fiddle with or nitpick here 😀

**Comment by genehack** [comment]
Very happy to see this PR!

**Review by genehack — APPROVED** [review]

**Comment by scottcain** [comment]
👍❤️

**Comment by cjfields** [comment]
> Do you care about the line wrapping of your plain text files?

That can be addressed (I actually used the web interface to drop this in).

**Comment by carandraug** [comment]
I only have to say that I think it makes more sense to link to the actual webpage describing the code the conduct instead of linking to another git repo. But the code of conduct page on the OBF is quite sparse https://www.open-bio.org/code-of-conduct/ and links to it as well.

**Comment by peterjc** [comment]
The OBF Code of Conduct *is* the document on GitHub, with full version history etc - something we don't have on the current website (we used to have this on MediaWiki but that has different trade offs).

**Comment by cjfields** [comment]
@hyphaltip @carandraug I can go ahead and merge if you think the update is fine; I primarily wanted any feedback in place before the merge, even if it's simply a checkmark.  

> I only have to say that I think it makes more sense to link to the actual webpage describing the code the conduct instead of linking to another git repo. But the code of conduct page on the OBF is quite sparse https://www.open-bio.org/code-of-conduct/ and links to it as well.

Yeah I actually think a nicely formatted version on the OBF web page would be great, though keeping up to sync with the official version in Github on the current website might be a challenge.

**Comment by cjfields** [comment]
I have gone ahead and approved this.  @hyphaltip @carandraug let me know if you have concerns or if you think the CoC needs any modifications.

**Pull request merged**
