### PR TITLE
new modules Bio::Tools::Alignment::Overview and Bio::DB::NextProt

### PR DESCRIPTION
**Pull request by prvst**
Some time ago I made the mistake of uploading to CPAN a module called Bio::Tools::Alignment::Overview, the module wasn't associated to bioperl but for some reason I decided to use the namespace anyway (yeah, I know...)

Now I'm organizing some projects and I decided to include the module to bioperl, so if you accept this pull request I will remove from PAUSE/CPAN the current module, so that you can upload it under bioperl.

Sorry for the noobish mistake =)

Cheers.

### CODE REVIEW

**Comment by fjossandon** [comment]
@cjfields : I locally downloaded this PR, merged it to master and executed the test suite.
The merge produced no conflicts, and all tests (including the ones added in this PR) executed without problems. The only thing is that this module requires `REST::Client`, so that would need to be added to Build %recommends.

Unless there is another concern, I think this is good to merge. ;)

**Comment by prvst** [comment]
hey, nice to see some feedback after so long =)

**Comment by cjfields** [comment]
Hi @prvst .  I thought the plan was to release it as a separate set of modules to CPAN (see https://github.com/bioperl/bioperl-live/pull/61#issuecomment-30439081), hence the long silence.  Well, that and I've been ridiculously busy.  

I see that it requires REST::Client and GD::Simple, which adds at least two dependencies to the distribution, which is the key problem since we're trying to reduce dependencies in core, a key point to the next release series.  We're more than happy to make a new repo for you in the bioperl namespace and set you up with commit rights for that as well as the main repo. Let us know.

**Comment by hlapp** [comment]
I notice that each of the two new pieces of functionality consist of essentially a single module (and file, plus the tests of course), and not because everything's crammed into one file but because they are fairly small and self-contained.

@cjfields I'm wondering what our strategy here is. Having everything in separate modules / packages even if they are exceedingly small is neither a bad one, nor one unheard of - that's basically what the nodeJS ecosystem prides itself for. But _are_ we actually moving to a nodeJS-like strategy? It'd be a rather dramatic (to put it lightly) change from where we're at now.

If the nodeJS-like ecosystem isn't what we're going for, I'm not sure that these two modules warrant their own repositories. They would add to the dependencies, yes, but only optional ones. I.e., by including these we aren't forcing their installation on anyone but those who want to use these modules. I'd be OK with that.

**Comment by cjfields** [comment]
@hlapp The purpose is really to place more power and responsibility with the original developers, both so they can make changes to their own code as well as make independent releases w/o being tied to the BioPerl core module releases.  

This doesn't mean they would need to exist independently (they could easily be part of the BioPerl org, so other devs can help contribute and make releases).  But I would like to both reduce the maintenance pressure on the core modules, which see infrequent releases, as well as enable others to both participate in the org and take a more direct ownership of their code.

We do have some precedence for this, with the bp-utils and Bio::Community projects, not to mention the BioPerl-network and DB code.  Not to mention @lstein code for Gbrowse

**Comment by cjfields** [comment]
Hi all, we're almost at the 10 year mark for this pull request (which I think we can safely close).  @prvst did you have any additional comments on it?

**Comment by prvst** [comment]
We'll that's a shame, I was hoping to discover if GitHub has some sort of achievement badge for a 10 year old PR 😁. 

No worries, Chris. Feel free to close.it.

Thanks.

**Pull request closed without merging**
